name: Deploy to Heroku

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "nazlicankurtben@gmail.com"
        git config --global user.name "nazlicankurtben"

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: jobop-frontend
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ env.HEROKU_APP_NAME }}.git
        git fetch heroku main || true
        git checkout -B heroku-deploy
        git merge -X ours heroku/main --allow-unrelated-histories || true
        git push heroku heroku-deploy:main --force
